name = "closeai-proxy"
main = "src/index.ts"
type = "javascript"
compatibility_date = "2024-06-01"
workers_dev = false

account_id = "${CF_ACCOUNT_ID}"
zone_id = "${CF_ZONE_ID}"
route = "${CF_ROUTE}"

[vars]
OPENAI_API_KEY = "${OPENAI_API_KEY}"
# Этот проект может поддерживать маскирование ключей внутри прокси
ACCESS_TOKEN = "${ACCESS_TOKEN}"
